// <auto-generated />
using System;
using GamesGlobal.ShoppingList.Infrastructure.DataAccess.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamesGlobal.ShoppingList.Infrastructure.DataAccess.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<long>("LoginSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LoginSessionId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginSessionId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshToken_Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoleId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", "identity");

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Super Admin"
                        },
                        new
                        {
                            RoleId = 2L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "End User"
                        },
                        new
                        {
                            RoleId = 3L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Auditor"
                        });
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.RolePermission", b =>
                {
                    b.Property<long>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RolePermissionId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Permission")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", "identity");

                    b.HasData(
                        new
                        {
                            RolePermissionId = 1L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Permission = -1L,
                            PermissionName = "All",
                            RoleId = 1L
                        },
                        new
                        {
                            RolePermissionId = 2L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Permission = 1L,
                            PermissionName = "Shopping Items Self Read/Write",
                            RoleId = 2L
                        },
                        new
                        {
                            RolePermissionId = 3L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Permission = 4L,
                            PermissionName = "User Roles And Permissions Read",
                            RoleId = 3L
                        });
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("IX_User_UserCode");

                    b.ToTable("Users", "identity");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "johndoe@example.gamesglobal",
                            FirstName = "Test",
                            LastName = "Shopper",
                            Password = "AQAAAAIAAYagAAAAEMjOMRX3KUP+HAnuNXdSUSKWXkho+10WudwJqneRzr8rgcd4twupbzUOSvho8I5qgA==",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            UserId = 2L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.gamesglobal",
                            FirstName = "Super",
                            LastName = "Admin",
                            Password = "AQAAAAIAAYagAAAAEMjOMRX3KUP+HAnuNXdSUSKWXkho+10WudwJqneRzr8rgcd4twupbzUOSvho8I5qgA==",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            UserId = 3L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "auditor@example.gamesglobal",
                            FirstName = "Auditor",
                            LastName = "General",
                            Password = "AQAAAAIAAYagAAAAEMjOMRX3KUP+HAnuNXdSUSKWXkho+10WudwJqneRzr8rgcd4twupbzUOSvho8I5qgA==",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        });
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 2L
                        },
                        new
                        {
                            UserId = 2L,
                            RoleId = 1L
                        },
                        new
                        {
                            UserId = 3L,
                            RoleId = 3L
                        });
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.RolePermission", b =>
                {
                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.UserRole", b =>
                {
                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Identity.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
