<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Constants\**" />
    <EmbeddedResource Remove="Constants\**" />
    <None Remove="Constants\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Minio" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataAccess\Application\Migrations\" />
    <Folder Include="DataAccess\Identity\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DataAccess\Application\SeedData\ShoppingItems.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GamesGlobal.ShoppingList.Application\GamesGlobal.ShoppingList.Application.csproj" />
    <ProjectReference Include="..\GamesGlobal.ShoppingList.BusinessDomain\GamesGlobal.ShoppingList.BusinessDomain.csproj" />
  </ItemGroup>

</Project>
