<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Constants\**" />
    <EmbeddedResource Remove="Constants\**" />
    <None Remove="Constants\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataAccess\Application\Migrations\" />
    <Folder Include="DataAccess\Identity\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GamesGlobal.ShoppingList.BusinessDomain\GamesGlobal.ShoppingList.BusinessDomain.csproj" />
  </ItemGroup>

</Project>
