@url=create-shopping-item

POST {{baseUrl}}/{{url}}
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: */*

{
  "name": "Milo",
  "Description": "Nestlé MILO is a signature chocolate-malt beverage powder designed to be mixed with hot or cold milk or water for a rich, nourishing energy drink"
}
