// <auto-generated />
using System;
using GamesGlobal.ShoppingList.Infrastructure.DataAccess.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace GamesGlobal.ShoppingList.Infrastructure.DataAccess.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906164911_ShoppingItemsFullSearchIndex")]
    partial class ShoppingItemsFullSearchIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItem", b =>
                {
                    b.Property<long>("ShoppingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ShoppingItemId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embeddings")
                        .HasColumnType("vector(768)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCode")
                        .HasColumnType("uuid");

                    b.HasKey("ShoppingItemId");

                    b.HasIndex("UserCode");

                    b.HasIndex("Name", "Description")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name", "Description"), "GIN");

                    b.ToTable("ShoppingItems");

                    b.HasData(
                        new
                        {
                            ShoppingItemId = 5L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "It is made of high-quality PVC material and stands about 22cm tall. The figure features carefully handmade painting, vivid character design, and fine details of her appearance, expression and costume.This is a handmade collectible figure of Kamado Nezuko from the popular anime Demon Slayer.",
                            Name = "Demon Slayer: Kimetsu no Yaiba Kamado Nezuko Handmade Figure 22cm",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 6L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "This is an electric remote-controlled speedboat toy, suitable for outdoor use in ponds, lakes, and swimming pools. It's suitable for children and model enthusiasts.",
                            Name = "2 Pieces of High-Speed Remote Control Boat, 2.4G Wireless Remote Control",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 7L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
                            Name = "Powder Canister",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 8L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
                            Name = "Red Lipstick",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 9L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
                            Name = "Red Nail Polish",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 10L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It is a versatile fragrance suitable for everyday wear.",
                            Name = "Calvin Klein CK One",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 11L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Dad's Choice Awards 2013 - Winner. This model is a greatly simplified version of a real V8 car engine featuring realistic V8 sound and illuminating spark plugs. Contains over 250 pieces and all that you need to assemble the model. Comes with a style manual giving you step by step instruction as well as interesting information about V8 engines.",
                            Name = "Machine Works V8 Engine Plastic Model Kit",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 12L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Intel Core Ultra 7 258V processor for powerful performance. 14 WUXGA (1920×1200) IPS display with crisp visuals. 32GB LPDDR5x memory for seamless multitasking. 1TB NVMe SSD for fast storage and boot times. Backlit keyboard for easier typing in low light. Integrated Intel Arc Graphics 140V for enhanced visuals. Windows 11 Pro with Copilot+ AI productivity features",
                            Name = "Lenovo ThinkPad E14 Gen 7 14 Core Ultra 7 32GB 1TB Laptop",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 13L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "With a manual override switch, this smart meter allows you to monitor your geyser/pool pump/ air conditioner etc power consumption of up to 63A, helping you pinpoint the factors driving up your electricity bill. Features include live, hourly, daily, monthly, and yearly consumption tracking. You can remotely control your geyser from anywhere via the eWelink app, available for both iOS and Android.",
                            Name = "ES Echosmart SY2 Smart WiFi Geyser timer-eWelink app - with energy metering",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 14L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The ACEBOTT DC Motor Driver Module enables precise control over the rotation direction and speed of a DC motor through input signals. It features two control pins-IN+ for clockwise rotation and IN- for counterclockwise rotation-allowing directional control by applying high or low signals to each pin.",
                            Name = "ACEBOTT DC Motor Driver Module",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 35L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Lenovo L470 is a business-class laptop built for reliability, security, and performance. Powered by a 6th Gen Intel Core i5 processor, 8GB RAM, and a fast 256GB SSD, it's a great solution for professionals and students seeking performance on a budget.",
                            Name = "Certified Pre-Owned Lenovo L470 - Intel Core i5 6th Gen 8GB RAM 256GB SSD",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 36L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Experience a smarter lifestyle with the HONOR Watch X5i. Featuring a large 1.97-inch AMOLED display, ultra-lightweight design, 21-day battery life, Bluetooth calling and comprehensive health tracking, this smartwatch combines style, performance and everyday convenience. The HONOR Watch X5i is designed for users who want a stylish smartwatch with powerful features and long-lasting performance. Its expansive AMOLED display delivers vibrant visuals with a smooth viewing experience, while the lightweight body ensures comfortable all-day wear.",
                            Name = "HONOR X5i Smart Watch | Strava, Google Fit, Apple Health Compatible - White",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 37L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Create professional-quality photos, videos, live streams and social media content with the NESTY NRL-77 14Inch LED Studio Ring Light. Designed to provide bright, soft and even illumination, this large ring light helps reduce harsh shadows and gives your face or subject a clean, professional appearance Create professional-quality photos, videos, live streams and social media content with the NESTY NRL-77 14Inch LED Studio Ring Light. Designed to provide bright, soft and even illumination, this large ring light helps reduce harsh shadows and gives your face or subject a clean, professional appearance..",
                            Name = "14 Inch Studio Ring Light LED Light For Video Photography Lighting NESTY",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 38L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Three-sided Infinite Mirror ARGB light effect the side infinity mirrors on the left and right sides of the fan are based on infinite geometry Multiple layers 0.5mm apart are visible in the circular infinity mirror at the center of the fan.",
                            Name = "20mm ARGB Case Fans with 24 LED Lights PWM Control & ARGB Effect",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 39L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Experience fast, fluid and detailed gameplay with the Philips Evnia 24M2N2100NF Gaming Monitor.Its 23.8-inch IPS panel delivers crisp Full HD visuals with realistic colour and wide viewing angles. A maximum refresh rate of 144Hz redraws the image more frequently than a standard display, helping fast-moving gameplay appear smoother and easier to follow.",
                            Name = "Philips Evnia 23.8\" FHD IPS 144Hz Gaming Monitor.",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 40L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Enjoy a clean, comfortable, and cable-free workspace with the JEQANG JW-392 Wireless Keyboard and Mouse Combo. Featuring an ultra-thin keyboard, ergonomic mouse, and reliable 2.4GHz wireless connectivity, this practical combo is ideal for home, office, studying, and everyday computer use.",
                            Name = "Thin Wireless Keyboard Mouse",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 78L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
                            Name = "Knoll Saarinen Executive Conference Chair",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 79L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
                            Name = "Wooden Bathroom Sink With Mirror",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 80L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
                            Name = "Apple",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 81L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
                            Name = "Beef Steak",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 82L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
                            Name = "Cat Food",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 83L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Fresh and tender chicken meat, suitable for various culinary preparations.",
                            Name = "Chicken Meat",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 84L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Versatile cooking oil suitable for frying, sauteing, and various culinary applications.",
                            Name = "Cooking Oil",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 85L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
                            Name = "Cucumber",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 86L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
                            Name = "Dog Food",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 87L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
                            Name = "Eggs",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 88L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Quality fish steak, suitable for grilling, baking, or pan-searing.",
                            Name = "Fish Steak",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 89L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
                            Name = "Green Bell Pepper",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 90L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Built with an advanced CMOS sensor, this compact digital camera supports 4K UHD video recording and 64MP photography. It delivers sharp, detailed footage to record natural scenery, family gatherings and all your precious moments.Featuring a 2.8-inch IPS screen, the camera comes with a handy recording pause function and supports recording while charging. With the bundled Type-C cable, you can not only transfer files to your PC easily, but also turn the camera into a functional webcam.",
                            Name = " Camera with 32GB TF Card, Auto Focus with 16X Digital Zoomr",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 91L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
                            Name = "Honey Jar",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 92L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
                            Name = "Ice Cream",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 93L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
                            Name = "Juice",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 94L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "These refurbished devices sold here have been put through a comprehensive refurbishment process and have been rigorously tested for functionality and quality to ensure performance comparable to new products. Most of these devices, and re-installed and updated software and drivers on all of them during the refurbishment process - ensuring optimal performance. Where necessary, parts have been replaced. Refurbished devices do not come with original packaging and manuals. Refurbished Intel NUC Intel i5 10th Gen - 16GB DDR4 2666 - 1TB SSD M.2 NVMe - WiFi",
                            Name = "Intel NUC Intel i5 10th Gen 16GB ",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        });
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItemDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShoppingItemId")
                        .HasColumnType("bigint");

                    b.HasKey("DocumentId", "ShoppingItemId");

                    b.HasIndex("ShoppingItemId");

                    b.ToTable("ShoppingItemDocuments", "public");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItemDocument", b =>
                {
                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItem", "ShoppingItem")
                        .WithMany()
                        .HasForeignKey("ShoppingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ShoppingItem");
                });
#pragma warning restore 612, 618
        }
    }
}
