// <auto-generated />
using System;
using GamesGlobal.ShoppingList.Infrastructure.DataAccess.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace GamesGlobal.ShoppingList.Infrastructure.DataAccess.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905124713_ShoppingItemAndEmbeddings")]
    partial class ShoppingItemAndEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItem", b =>
                {
                    b.Property<long>("ShoppingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ShoppingItemId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embeddings")
                        .HasColumnType("vector(768)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCode")
                        .HasColumnType("uuid");

                    b.HasKey("ShoppingItemId");

                    b.HasIndex("UserCode");

                    b.ToTable("ShoppingItems");

                    b.HasData(
                        new
                        {
                            ShoppingItemId = 5L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
                            Name = "Essence Mascara Lash Princess",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 6L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it is convenient for on-the-go makeup application.",
                            Name = "Eyeshadow Palette with Mirror",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 7L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
                            Name = "Powder Canister",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 8L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
                            Name = "Red Lipstick",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 9L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
                            Name = "Red Nail Polish",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 10L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It is a versatile fragrance suitable for everyday wear.",
                            Name = "Calvin Klein CK One",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 11L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
                            Name = "Chanel Coco Noir Eau De",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 12L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
                            Name = "Dior J'adore",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 13L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Dolce Shine by Dolce and Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It is a joyful and youthful scent.",
                            Name = "Dolce Shine Eau de",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 14L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It is a modern and romantic scent.",
                            Name = "Gucci Bloom Eau de",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 35L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
                            Name = "Essence Mascara Lash Princess",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 36L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it is convenient for on-the-go makeup application.",
                            Name = "Eyeshadow Palette with Mirror",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 37L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
                            Name = "Powder Canister",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 38L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
                            Name = "Red Lipstick",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 39L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
                            Name = "Red Nail Polish",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 40L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It is a versatile fragrance suitable for everyday wear.",
                            Name = "Calvin Klein CK One",
                            UserCode = new Guid("00c2f66a-e396-4865-9338-d9cb8faff7d4")
                        },
                        new
                        {
                            ShoppingItemId = 78L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
                            Name = "Knoll Saarinen Executive Conference Chair",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 79L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
                            Name = "Wooden Bathroom Sink With Mirror",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 80L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
                            Name = "Apple",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 81L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
                            Name = "Beef Steak",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 82L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
                            Name = "Cat Food",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 83L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Fresh and tender chicken meat, suitable for various culinary preparations.",
                            Name = "Chicken Meat",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 84L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Versatile cooking oil suitable for frying, sauteing, and various culinary applications.",
                            Name = "Cooking Oil",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 85L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
                            Name = "Cucumber",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 86L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
                            Name = "Dog Food",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 87L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
                            Name = "Eggs",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 88L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Quality fish steak, suitable for grilling, baking, or pan-searing.",
                            Name = "Fish Steak",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 89L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
                            Name = "Green Bell Pepper",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 90L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
                            Name = "Green Chili Pepper",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 91L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
                            Name = "Honey Jar",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 92L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
                            Name = "Ice Cream",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 93L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
                            Name = "Juice",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        },
                        new
                        {
                            ShoppingItemId = 94L,
                            Created = new DateTime(2025, 4, 30, 9, 41, 2, 53, DateTimeKind.Utc),
                            Description = "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
                            Name = "Kiwi",
                            UserCode = new Guid("54e66112-3ef2-4ed5-8fb7-d5ca167f07b1")
                        });
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItemDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShoppingItemId")
                        .HasColumnType("bigint");

                    b.HasKey("DocumentId", "ShoppingItemId");

                    b.HasIndex("ShoppingItemId");

                    b.ToTable("ShoppingItemDocuments", "public");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItemDocument", b =>
                {
                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItem", "ShoppingItem")
                        .WithMany()
                        .HasForeignKey("ShoppingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ShoppingItem");
                });
#pragma warning restore 612, 618
        }
    }
}
