// <auto-generated />
using System;
using GamesGlobal.ShoppingList.Infrastructure.DataAccess.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamesGlobal.ShoppingList.Infrastructure.DataAccess.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904114659_EnablePgvector")]
    partial class EnablePgvector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItem", b =>
                {
                    b.Property<long>("ShoppingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ShoppingItemId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCode")
                        .HasColumnType("uuid");

                    b.HasKey("ShoppingItemId");

                    b.HasIndex("UserCode");

                    b.ToTable("ShoppingItems");

                    b.HasData(
                        new
                        {
                            ShoppingItemId = 1L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Blue denim jean, medium size.",
                            Name = "Pants",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 2L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "White plain shirt, medium size.",
                            Name = "Shirt",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        });
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItemDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShoppingItemId")
                        .HasColumnType("bigint");

                    b.HasKey("DocumentId", "ShoppingItemId");

                    b.HasIndex("ShoppingItemId");

                    b.ToTable("ShoppingItemDocuments", "public");
                });

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItemDocument", b =>
                {
                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItem", "ShoppingItem")
                        .WithMany()
                        .HasForeignKey("ShoppingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ShoppingItem");
                });
#pragma warning restore 612, 618
        }
    }
}
