// <auto-generated />
using System;
using GamesGlobal.ShoppingList.Infrastructure.DataAccess.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamesGlobal.ShoppingList.Infrastructure.DataAccess.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamesGlobal.ShoppingList.BusinessDomain.Entities.ShoppingItem", b =>
                {
                    b.Property<long>("ShoppingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ShoppingItemId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserCode")
                        .HasColumnType("uuid");

                    b.HasKey("ShoppingItemId");

                    b.HasIndex("UserCode");

                    b.ToTable("ShoppingItems");

                    b.HasData(
                        new
                        {
                            ShoppingItemId = 1L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Blue denim jean, medium size.",
                            Name = "Pants",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        },
                        new
                        {
                            ShoppingItemId = 2L,
                            Created = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "White plain shirt, medium size.",
                            Name = "Shirt",
                            UserCode = new Guid("d3b07384-d9a0-4f1e-8c2e-1f2b3c4d5e6f")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
