@url=identity/update-role-permissions


POST {{baseUrl}}/{{url}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: */*

{
  "RoleId": 3,
  "RoleName": "Agent",
  "Permissions": [
    {
      "Value": 1
    },
        {
      "Value": 2
    },
        {
      "Value": 4
    }
  ]
}