@url=update-shopping-item

POST {{baseUrl}}/{{url}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: */*

{
  "shoppingItemId": 98,
  "name": "Choc Brownie",
  "Description": "Swiss Chocolate delight"
}